//------------------------------------------------------------------------
// Copyright(c) 2023 Sommet.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Control Master.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Control Master VST3 (64Bit)"
#else
#define stringFileDescription	"Control Master VST3"
#endif
#define stringCompanyName		"Sommet\0"
#define stringLegalCopyright	"Copyright(c) 2023 Sommet."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
