# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build the project to a VST3 plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}\build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}\build --target Control_Master --config ${{env.BUILD_TYPE}}

    - name: Archiving binaries
      run: Compress-Archive -Path ${{github.workspace}}\build\VST3\${{env.BUILD_TYPE}}\Control_Master.vst3\* -DestinationPath ControlVST3.zip

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ControlVST3
        path: ControlVST3.zip

  # We need to create a tag for the release
  # release:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Download artifact
  #     uses: actions/download-artifact@master
  #     with:
  #       name: ControlVST3.zip
  #       path: ControlVST3.zip

  #   - name: Create Release
  #     id: create_release
  #     uses: softprops/action-gh-release@master
  #     with:
  #       body: |
  #         Release notes and description.
  #       files: ControlVST3.zip
